version: '3'

services:
  postgres:
    image: postgres:12.0-alpine
    container_name: postgres-eleven-labs
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: eleven-labs-api